Ensure `plot_emission_intensity` with input data having `label` column, outputs custom colour scale with expected order
RMI-PACTA/r2dii.plot pull request #537
Opened 2024-01-24 18:06 UTC by jdhoffa

Maybe closes #535

2024-01-25 10:38 UTC, jdhoffa commented
Note: My test isn't working as expected 😂

2024-01-25 12:06 UTC, jdhoffa commented
@MonikaFu what I did here was, in the `add_label` function, I added a condition that checks if the `metric(data)` column to which the `label` column corresponds is factored. If it is, it then factors the `label` column with the same order.

2024-01-26 16:06 UTC, MonikaFu requested changes

2024-01-26 16:15 UTC, jdhoffa commented on tests/testthat/test-plot_emission_intensity.R
> +test_that("with data with `label` column, outputs custom colour scale with expected order (#535)", {
Hmm, I thought "outputs custom colour scale" implied that it was a custom colour scale? 

But happy to make it more clear if you think my wording was confusing

2024-01-26 16:17 UTC, jdhoffa commented on tests/testthat/test-plot_emission_intensity.R
> +test_that("with data with `label` column, outputs custom colour scale with expected order (#535)", {
Do you like
"with data with `label` column and with `scale_colour_r2dii`, outputs expected labels and colours"

2024-01-26 16:18 UTC, jdhoffa commented on R/utils.R
>  add_label_if_missing <- function(data) {
Good point!

2024-01-26 16:19 UTC, jdhoffa commented on R/utils.R
>  add_label_if_missing <- function(data) {
`add_label_and_factor_if_necessary`? lol

2024-01-26 16:57 UTC, MonikaFu commented on tests/testthat/test-plot_emission_intensity.R
> +test_that("with data with `label` column, outputs custom colour scale with expected order (#535)", {
Yes!

2024-01-26 17:00 UTC, MonikaFu commented on R/utils.R
>  add_label_if_missing <- function(data) {
I'm happy with how you resolved this! however, I see all checks failing. I guess something to look into.

2024-01-26 17:01 UTC, jdhoffa commented on tests/testthat/test-plot_emission_intensity.R
> +test_that("with data with `label` column, outputs custom colour scale with expected order (#535)", {
Should be resolved :-)

2024-01-29 09:37 UTC, jdhoffa commented on R/utils.R
>  add_label_if_missing <- function(data) {
Yup, lol hasty work. 

I was returning `data$label` instead of `data`. 

Fixed :-)

2024-01-29 09:40 UTC, jdhoffa commented
@MonikaFu I'm inclined to NOT update the `NEWS.md` here, since we are fixing a bug that was introduced only in dev, so no user-facing changes should be observed since the previous release, do you agree?

2024-01-29 09:45 UTC, jdhoffa commented
The old release failing checks to be handled here: https://github.com/RMI-PACTA/r2dii.plot/issues/540

2024-01-29 14:02 UTC, merged