Extract `prep_*` functions from `plot_*` functions
RMI-PACTA/r2dii.plot pull request #543
Opened 2024-01-30 15:45 UTC by jdhoffa

Closes #465

2024-01-30 17:10 UTC, jdhoffa commented
@MonikaFu I am working towards completing this, but I don't understand what the `env` argument for `prep_techmix` achieves. It seems to not be user-facing, but I'm curious how it should be handled. 

https://github.com/RMI-PACTA/r2dii.plot/blob/bc4814146bd0f8668b4d85c40a5b582774141a91/R/plot_techmix.R#L59-L70

2024-02-01 11:00 UTC, MonikaFu commented
You're right, it is not supposed to be user-facing. The variable is used in internal functions in order to return more meaningful errors. It passes the environment in which the function was called to the inside of the functions so that the name of variable that was used as for example, `data` argument is known and shown to the user in an error message. It should not be part of `prep_*` functions when they become user-facing.

2024-02-01 11:20 UTC, jdhoffa commented
Thanks for the context @MonikaFu , I will have a look at what you did, and come back if I have questions :-)

2024-02-02 14:27 UTC, jdhoffa commented
Ooof @MonikaFu this is a huge undertaking it turns out. 
I have done a good chunk of the extraction and refactoring (including updating tests) and I think we are at a functional step. 

I have 2 big TO-DOs left:

- [ ] Complete the deprecation process using the `lifecycle` package
- [ ]  Review and check all FIXMEs (I left two tests empty to test some behaviour that I wasn't sure how to test at the time. Going to come back to those in a moment)

But in the mean-time, when you're feeling better, I would love a quick review already, as a lot of files have been touched.

2024-02-02 14:27 UTC, jdhoffa commented on NEWS.md
> +`prep_*()` functions (#465).
Feel free to re-word this. I wonder if it maybe deserves more explanation in the `NEWS.md` as it is a Breaking and user-facing API change.

2024-02-02 14:28 UTC, jdhoffa commented on R/plot_emission_intensity.R
> +#' @param data A data frame like the output of `prep_emission_intensity()`.
Most `plot_*` functions don't have that many arguments, and most get passed to the `prep_*` functions (you will see a similar trend with the tests.

2024-02-02 14:29 UTC, jdhoffa commented on R/plot_emission_intensity.R
> -#' )
Examples had to be hugely refactored. To recreate the `qplot_*` functionality, the arguments have to be passed to the corresponding `prep_*` function. I still thought the info was useful, so I made that the ONLY example. 

I can add more examples if you think it is useful.

2024-02-02 14:31 UTC, jdhoffa commented on R/plot_emission_intensity.R
> -  )
I have removed the deprecation warnings entirely. I have a TODO to re-add an appropriate message (I think? do I even need to?? I need to look into how to do this properly).

2024-02-02 14:32 UTC, jdhoffa commented on R/plot_emission_intensity.R
> +  check_emission_intensity(data, env = env)
`check_plot_emission_intensity` and `check_prep_emission_intensity` ended up being identical, so I just refactored it out entirely.

I do think it's good to do checks on both functions, since they are both now exported.

2024-02-02 14:36 UTC, jdhoffa commented on R/plot_techmix.R
> -
I was refactoring to ensure all functions that were relevant to `prep_*` or `plot_*` were in the appropriate place.
While doing this, I noticed that these are used by multiple functions so i moved them to `utils.R`

2024-02-02 14:37 UTC, jdhoffa commented on R/plot_trajectory.R
> -
All of these are now relevant to `prep_trajectory`

2024-02-02 14:38 UTC, jdhoffa commented on R/plot_trajectory.R
>    )
git diff is getting confused here, this was a pure refactor

2024-02-02 14:39 UTC, jdhoffa commented on R/plot_trajectory.R
> -  data_scenarios
This logic was left alone, and purely refactored to `prep_trajectory`

2024-02-02 14:39 UTC, jdhoffa commented on R/qplot_emission_intensity.R
> +  check_emission_intensity(data, env = env)
See above: pure refactor

2024-02-02 14:40 UTC, jdhoffa commented on R/qplot_techmix.R
> -      env = env
`env` is no longer a user-facing argument of `prep_techmix`

2024-02-02 14:40 UTC, jdhoffa commented on R/qplot_trajectory.R
> +}
Added a new check, since `qplot_trajectory` now needs the check conditions for both `prep` and `plot`

2024-02-02 14:43 UTC, jdhoffa commented on tests/testthat/test-plot_emission_intensity.R
> -
Many tests were moved to the more appropriate place (e.g. if "too many line" handling is in the `prep_*` function, it has been moved there.

2024-02-02 14:44 UTC, jdhoffa commented on tests/testthat/test-plot_emission_intensity.R
> -
All "API change" warning tests have been removed. See my "figure out deprecation" TODO

2024-02-02 14:44 UTC, jdhoffa commented on tests/testthat/test-plot_techmix.R
> -
Tests migrated to `prep`

2024-02-05 08:31 UTC, jdhoffa commented
Regarding the deprecation process, my assessment is the following:
* We have adequately warned users that we plan to change the API of an existing function (a breaking change)
* Since we are not yet in version `1.0.0` of `r2dii.plot`, we have still allowed ourselves the opportunity to have breaking changes
* We will need to do a minor version bump for sure, as per SemVer
* I do not think we need any further deprecation messages (I think it's fine to simply remove them all)

2024-02-05 08:36 UTC, jdhoffa commented on tests/testthat/test-plot_trajectory.R
> +  # expect_error(plot_trajectory(bad_region), "bad_region")
I will need some support here. I seem to have broken this test (it no longer errors as expected), and I am sure it has to do with the `.env` argument. Would love to pair with you for ~20min to try to figure this bit out :-)

2024-02-05 11:06 UTC, jdhoffa commented
There is a NOTE when running R CMD check:
"Namespace in Imports field not imported from: ‘forcats’ All declared Imports should be used."

I think this note isn't related to this PR, and should be tackled in a separate issue/ PR.

2024-02-12 13:07 UTC, MonikaFu commented on R/plot_emission_intensity.R
> -  )
I'd say it would be great if we could add an informative error message in case the user calls plot on unprepped data.  Also - maybe we should write a blog post explaining how the functions work now and why we introduced this change? I guess I could write it if needed.

2024-02-12 13:36 UTC, jdhoffa commented on R/plot_emission_intensity.R
> -  )
We don't have a blog currently :-D lol

2024-02-12 14:08 UTC, MonikaFu requested changes
Thanks for your work! See my comments. Happy to discuss verbally as well.

2024-02-12 14:08 UTC, MonikaFu commented on tests/testthat/_snaps/plot_techmix.md
> -    x Provided: a, b.
These are still relevant I'd say. Or do we move it all to `prep_()` and add a check for if the data have been prepped instead?

2024-02-12 14:08 UTC, MonikaFu commented on tests/testthat/_snaps/plot_techmix.md
> -
Still relevant I'd say?

2024-02-12 14:08 UTC, MonikaFu commented on tests/testthat/_snaps/prep_emission_intensity.md
> +# with too many lines to plot errors gracefully
I'd say this is more of a plot check than a prep check still.

2024-02-12 14:08 UTC, MonikaFu commented on tests/testthat/test-plot_emission_intensity.R
> -
We need to update the message or move the check I'd say. It is not very intuitive to have a message about too many lines to plot in a function that is not plot.

2024-02-12 14:08 UTC, MonikaFu commented on tests/testthat/test-plot_techmix.R
> -test_that("with zero-row data errors gracefully", {
I guess we should keep this test here as well? Someone might pass a zero row data to plot still.

2024-02-12 14:08 UTC, MonikaFu commented on tests/testthat/test-plot_techmix.R
> -
potentially we might want to keep them in both? Not sure.

2024-02-12 14:08 UTC, MonikaFu commented on tests/testthat/test-plot_trajectory.R
> +  # expect_error(plot_trajectory(bad_region), "bad_region")
let's

2024-02-12 14:10 UTC, MonikaFu commented
@jdhoffa see my review on the draft. Also - given these changes we need to update the documentation on the package website. I'd say let's do it in a separate PR because this one is already huge. Also happy to do it myself. Should we open an issue for it?

2024-02-12 14:12 UTC, jdhoffa commented on R/plot_emission_intensity.R
> +  plot_emission_intensity_impl(data)
Un-related: This would also close #529 :-)

2024-02-12 14:16 UTC, jdhoffa commented on R/plot_trajectory.R
> -                            center_y = FALSE,
Got it!

2024-02-13 15:41 UTC, jdhoffa commented on R/plot_emission_intensity.R
> +  check_emission_intensity(data, env = env)
I agree in principle that the `checks` likely should be different as they test different input. However in practice, the were checking the presence of the exact same columns. 

That to me suggests that `check_plot_emission_intensity` and `check_prep_emission_intensity` likely should be expanded to include more precise checking, but I think that is out of scope for this PR. 

I will open a new issue to that effect.

2024-02-13 15:43 UTC, jdhoffa commented on R/plot_emission_intensity.R
> +  check_emission_intensity(data, env = env)
Would you like me to split them back into `check_plot_emission_intensity` and `check_prep_emission_intensity` here? Recognizing that they would just be wrapping the same checks?

2024-02-13 16:57 UTC, jdhoffa commented on R/plot_trajectory.R
> -
I believe this is done

2024-02-13 16:58 UTC, jdhoffa commented on R/plot_trajectory.R
> -  data_scenarios
I believe this is done

2024-02-14 14:00 UTC, MonikaFu commented on R/plot_emission_intensity.R
> +  plot_emission_intensity_impl(data)
yup! Two birds with one stone or something

2024-02-14 14:03 UTC, MonikaFu commented on R/plot_emission_intensity.R
> +  check_emission_intensity(data, env = env)
They used to check for the same things because they were both using unprepped data. But now since `plot` requires prep data I'd expect that it's checks should change and check if the data passed to it indeed is prepped.

2024-02-14 14:20 UTC, jdhoffa commented on R/plot_emission_intensity.R
> +  check_emission_intensity(data, env = env)
Will be handled in #548

2024-02-14 14:34 UTC, jdhoffa commented on NEWS.md
> +`prep_*()` functions (#465).
@MonikaFu to reword this if you like!

2024-02-14 14:35 UTC, jdhoffa commented on R/plot_emission_intensity.R
> -  )
I wonder if this should also be handled in #548 ?

2024-02-14 14:37 UTC, jdhoffa commented on R/qplot_trajectory.R
> +}
NIT: I actually think that may be a bit of a dangerous assumption. I tend to think that any exported function should have it's own input checks. 

Consider the (unlikely) case that we decide to deprecate the `prep_*` and `plot_*` functions, and decide to remove all of the checks from them. `qplot_*` would not realize this, and would be left checkless.

But of course, you are maintainer, and if you would prefer I remove the checks here I am happy to do so!

2024-02-14 14:46 UTC, jdhoffa commented on tests/testthat/test-plot_emission_intensity.R
> -
Ok so, to move this test to `plot_emission_intensity`, I had to update the checks (so that the lin check only occurs on plot, which totally makes sense). 

Doing so split the `check_*_emission_intensity` function up again, as there is now 1 additional check that occurs only for `plot_emission_intensity`. However, I will leave #548 open, as I imagine we should still add many checks  to prove that `plot_*` isn't accepting un-prepared data...

2024-02-14 14:47 UTC, jdhoffa commented on tests/testthat/test-plot_techmix.R
> -
I think this should be handled in #548, when we add more checks to the`prep_*` and `plot_*` functions (we can also add tests that ensure each check functions as expected.

2024-02-14 14:48 UTC, jdhoffa commented
Probably closes #529

2024-02-14 14:48 UTC, jdhoffa commented on tests/testthat/test-plot_techmix.R
> -test_that("with zero-row data errors gracefully", {
I think we should handle this also in #548 when we add more checks (and corresponding tests)

2024-02-14 14:50 UTC, jdhoffa commented
There is a R CMD CHECK note that I believe is unrelated to this PR. Relates to #547

2024-02-14 16:47 UTC, jdhoffa commented on R/qplot_trajectory.R
> +}
Closing a resolved, see all the `qplot_` functions now :-)

2024-02-15 10:18 UTC, MonikaFu requested changes

2024-02-15 10:18 UTC, MonikaFu commented on R/plot_emission_intensity.R
> -  )
Yes, I agree, it should be part of the checks in #548 .

2024-02-15 10:18 UTC, MonikaFu commented on R/qplot_emission_intensity.R
> +  check_prep_emission_intensity(data, env = env)
just to confirm - you are calling the checks here (there are also inside `prep_emission_intensity` in order to be able to pass the right `env` to it? Maybe long term it should be handled in a more elegant way. Now we are calling the checks twice.

2024-02-15 10:18 UTC, MonikaFu commented on R/plot_trajectory.R
>                              span_5yr = FALSE,
`span_5yr` should be part of `prep_trajectory`. The same as for `emission_intensity` and `techmix`.

2024-02-15 10:21 UTC, MonikaFu commented
@jdhoffa I see checks failing also due to changes in `r2dii.analysis`. It seems like there was a name change of some of output columns. We should not solve it in this PR but it should be solved as the demo datasets in `r2dii.plot` should follow the output of `r2dii.analysis`.

2024-02-15 10:22 UTC, jdhoffa commented on R/qplot_emission_intensity.R
> +  check_prep_emission_intensity(data, env = env)
Correct! 
NIT: For safety, I do believe calling input checks explicitly on any exported function is prudent (if inelegant), for reasons stated in a different comment. But leave it to you to manage as you see fit :-)

2024-02-15 10:23 UTC, jdhoffa commented
> @jdhoffa I see checks failing also due to changes in `r2dii.analysis`. It seems like there was a name change of some of output columns. We should not solve it in this PR but it should be solved as the demo datasets in `r2dii.plot` should follow the output of `r2dii.analysis`.

That is unexpected to me! I will look into it in `r2dii.analysis` and get back to you.

2024-02-15 11:22 UTC, jdhoffa commented
> @jdhoffa I see checks failing also due to changes in `r2dii.analysis`. It seems like there was a name change of some of output columns. We should not solve it in this PR but it should be solved as the demo datasets in `r2dii.plot` should follow the output of `r2dii.analysis`.

tl;dr: Broken checks are unrelated to this PR.

In case you are interested:

The failed checks are coming from a "breaking change" in `r2dii.data`, where we have changed the expected format of the NACE codes (cc @jacobvjk)

* The breaking change happened here (where we changed how we format NACE codes), this introduced the bug: https://github.com/RMI-PACTA/r2dii.data/pull/327
* This PR should fix it, by aligning `loanbook_demo` with the new `NACE` code: https://github.com/RMI-PACTA/r2dii.data/pull/338

2024-02-15 11:34 UTC, jdhoffa commented on R/plot_trajectory.R
>                              span_5yr = FALSE,
Done!

2024-02-15 11:34 UTC, jdhoffa commented
I will wait until https://github.com/RMI-PACTA/r2dii.data/pull/338 is merged before re-requesting a review, so that we make sure CI/CD works well.

2024-02-15 11:47 UTC, jdhoffa commented on R/plot_trajectory.R
>                              span_5yr = FALSE,
Done

2024-02-16 12:12 UTC, jdhoffa commented
All checks now passing, this is ready for review!

2024-02-16 13:31 UTC, MonikaFu approved these changes
LGTM. See my proposed change to `NEWS.md`.

2024-02-16 13:31 UTC, MonikaFu commented on NEWS.md
> +`prep_*()` functions (#465).
```suggestion
* All `plot_*()` functions have had the data preparation step extracted into 
`prep_*()` functions. This means that from now on `prep_*()` function needs
to be called on `data` prior to `plot_*()`. The APIs of `qplot_*()` functions stay 
unchanged (#465).
```

2024-02-16 14:12 UTC, MonikaFu approved these changes
LGTM

2024-02-16 15:18 UTC, jdhoffa commented
Going to wait for confirmation that this won't affect ongoing projects, then I will merge :-)

2024-02-16 17:06 UTC, jdhoffa commented
Confirmed by @daisy-pacheco and @jacobvjk
Merging!

2024-02-16 17:06 UTC, merged